name: Run Pytest for Django

on:
  push:
    branches:
        - main
        - "feature/**"
        - "unit-tests/**"
  pull_request:
    branches: 
        - main
        - "feature/**"
        - "unit-tests/**"
jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: 📥 Checkout code
        uses: actions/checkout@v3

      - name: 🐍 Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: 📦 Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install boto3

      - name: 🧪 Run pytest
        run: |
          mkdir -p test-results
          pytest --disable-warnings | tee test-results/pytest-results.txt
          exit ${PIPESTATUS[0]}

      - name: 📊 Upload test results
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: pytest-results
          path: test-results/

      #if failed invoke bedrock unit test agent
      - name: 💾 Invoke Bedrock Agent
        if: failure() && startsWith(github.ref, 'refs/heads/feature/')
        env:
          AWS_BEDROCK_AGENT_ID: ${{ secrets.AWS_BEDROCK_AGENT_ID }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_BEDROCK_AGENT_ALIAS_ID: ${{ secrets.AWS_BEDROCK_AGENT_ALIAS_ID }}
          AWS_REGION: us-east-1
        run: |
          branch_name=$(echo "${{ github.ref }}" | sed 's|refs/heads/||')
          repo_url="https://github.com/${{ github.repository }}/tree/$branch_name"
          echo $repo_url
          intro_text="Given feature branch url is: $repo_url"
          prompt_string=$(cat .github/prompt.txt)
          pytest_output=$(cat test-results/pytest-results.txt)
          short_commit_hash=$(git rev-parse --short HEAD)
          intro_text="Given feature branch url is: $repo_url and short commit hash is: $short_commit_hash"
          prompt="$intro_text $prompt_string $pytest_output"
          echo "$prompt"
          export PROMPT_TEXT="$prompt"
          python invoke_bedrock_agent.py
